config/routes.rb
Rails.application.routes.draw do
  get 'favs/index'

  get 'category/index'

  get 'festivals/index'

  get 'festivals/show'

  get 'vibes/index'
  get 'vibes/show'


  get 'categories/index'

  get 'artists/index'

  get 'artists/index'
  get 'artists/show'

  get 'categories/index'
  get 'categories/show'

  get 'collectives/index'
  get 'collectives/show'

  get 'favorites/index'

  get 'home/index'

  get 'items/index'
  get 'items/show'

  get 'map_quest/index'

  get 'messenger/index'

  get 'profiles/show'

  get 'regions/index'
  get 'regions/show'

  get 'super_search/index'



  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/favs_controller.rb
class FavsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/collectives_helper.rb
module CollectivesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/map_quest_helper.rb
module MapQuestHelper
end

app/helpers/messenger_helper.rb
module MessengerHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/super_search_helper.rb
module SuperSearchHelper
end

app/helpers/vibes_helper.rb
module VibesHelper
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class='container'>
    <div class='row'>
      <!-- whole night objective: get all the fitting + scaling right -->

        <div class="dropdown" id='explore_dropdown'>
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Explore
          </button>
          <!-- DOES NOT WORK AFTER LINKING TO PAGE, MUST REFRESH PAGE THEN IT WORKS AGAIN -->
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <ul id='explore_ul'>
              <li><%= link_to "Artists √", artists_index_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Categories √", categories_index_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Collectives √", collectives_index_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Festivals √", festivals_index_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Regions √", regions_index_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Vibes √", vibes_index_path, :class => 'dropdown-item' %></li>
              <li>—</li>
              <li><%= link_to "artist", artists_show_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Category √", categories_show_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "collective", collectives_show_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Item √", items_show_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "profile", profiles_show_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Region √", regions_show_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Vibe √", vibes_show_path, :class => 'dropdown-item' %></li>
              <li>—</li>
              <li><%= link_to "home", home_index_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "map quest", map_quest_index_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Messenger √", messenger_index_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Super Search √", super_search_index_path, :class => 'dropdown-item' %></li>
              <li><%= link_to "Treasure Chest √", favorites_index_path, :class => 'dropdown-item' %></li>
            </ul>
          </div>
        </div>


        <div class="input-group" id='navbar_searchbar'>
          <input type="text" class="form-control searchbar_element" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-secondary searchbar_element" type="button">Go!</button>
          </span>
        </div>





        <div class='navbar_btns' id='chat'><%= link_to messenger_index_path do %><%= image_tag "chat.svg", :id => 'chat_icon', :class => 'navbar_icon' %><% end %></div>
        <div class='navbar_btns' id='notifications'><%= image_tag "call_bell.svg", :id => 'notification_icon', :class => 'navbar_icon' %></div>
        <div class='navbar_btns' id='favorites'><%= link_to favorites_index_path do %><%= image_tag "heart_black_around.svg", :id => 'heart_icon', :class => 'navbar_icon' %><% end %></div>
        <div id='profile_badge'>
          <p id='profile_name'>Taylor</p>
          <%= image_tag "facebook_profile.jpg", :id => 'profile_pic' %>
        </div>

    </div>
  </div>
</nav>

<script>
  var window_width = $(window).width();
  var side_margin = (window_width - 555) / 2;
  $('#navbar_searchbar').css("left", side_margin );
</script>