config/routes.rb
Rails.application.routes.draw do
  get 'favs/index'

  get 'category/index'

  get 'festivals/index'

  get 'festivals/show'

  get 'vibes/index'
  get 'vibes/show'


  get 'categories/index'

  get 'artists/index'

  get 'artists/index'
  get 'artists/show'

  get 'categories/index'
  get 'categories/show'

  get 'collectives/index'
  get 'collectives/show'

  get 'favorites/index'

  get 'home/index'

  get 'items/index'
  get 'items/show'

  get 'map_quest/index'

  get 'messenger/index'

  get 'profiles/show'

  get 'regions/index'
  get 'regions/show'

  get 'super_search/index'



  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
  end
end

app/controllers/favs_controller.rb
class FavsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
  end
end

app/controllers/vibes_controller.rb
class VibesController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/collectives_helper.rb
module CollectivesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/map_quest_helper.rb
module MapQuestHelper
end

app/helpers/messenger_helper.rb
module MessengerHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/super_search_helper.rb
module SuperSearchHelper
end

app/helpers/vibes_helper.rb
module VibesHelper
end

app/views/categories/index.html.erb
<div class='page_title'>Categories</div>

<!-- <div id='category_entry_belt'>
</div> -->

<div id='container end_div'>
  <div class='row'>
    <div class='col-md-1'></div>
    <div class='col-md-2'>
      <div class='category_entry'>
        <%= link_to category_index_path do %>
          <%= image_tag "spiritnectar_1.jpg", :class => 'categories_entry_picture' %>
          <p class='entry_title_name'>Crafts</p>
        <% end %>
      </div>
    </div>
    <div class='col-md-2'>
      <div class='category_entry'>
        <%= link_to category_index_path do %>
          <%= image_tag "sewmuchlove_sexy_girl_1.jpg", :class => 'categories_entry_picture' %>
          <p class='entry_title_name'>Clothing</p>
        <% end %>
      </div>
    </div>
    <div class='col-md-2'>
      <div class='category_entry'>
        <%= link_to category_index_path do %>
          <%= image_tag "mugwort_1.jpg", :class => 'categories_entry_picture' %>
          <p class='entry_title_name'>Visual Art</p>
        <% end %>
      </div>
    </div>
    <div class='col-md-2'>
      <div class='category_entry'>
        <%= link_to category_index_path do %>
          <%= image_tag "secret_wood_1.jpg", :class => 'categories_entry_picture' %>
          <p class='entry_title_name'>Jewelry</p>
        <% end %>
      </div>
    </div>
    <div class='col-md-2'>
      <div class='category_entry'>
        <%= link_to category_index_path do %>
          <%= image_tag "cozo_1.jpg", :class => 'categories_entry_picture' %>
          <p class='entry_title_name'>Home Items</p>
        <% end %>
      </div>
    </div>
    <div class='col-md-1'></div>
  </div>
</div>

app/views/categories/show.html.erb
<div class='page_title'>Visual Art</div>

<div class='container feature_3_window' id='categories__feature_3_item_window'>
  <div class='row'>
    <div class='col-md-4 feature_3'>
      <%= link_to items_show_path do %>
        <%= image_tag "psy_healing.jpg", :class => 'feature_3_picture' %>
      <% end %>
    </div>
    <div class='col-md-4 feature_3'>
      <%= link_to items_show_path do %>
        <%= image_tag "lundesigns_moon_goddess.jpg", :class => 'feature_3_picture' %>
      <% end %>
    </div>
    <div class='col-md-4 feature_3'>
      <%= link_to items_show_path do %>
        <%= image_tag "SpiritBear.jpg", :class => 'feature_3_picture position_20_80' %>
      <% end %>
    </div>
  </div>
</div>

<div class='container feature_3_spaced_window'>
  <div class='row feature_3_spaced_row'>
    <div class='col-md-4 feature_3_spaced_container'>
      <%= image_tag "lun_designs_profile_pic.jpg", :class => 'feature_3_spaced_picture feature_3_spaced_picture--left' %>
    </div>
    <div class='col-md-4 feature_3_spaced_container'>
      <%= image_tag "mugwort_tiger.jpg", :class => 'feature_3_spaced_picture feature_3_spaced_picture--middle' %>
    </div>
    <div class='col-md-4 feature_3_spaced_container'>
      <%= image_tag "haiduk_selfie.jpg", :class => 'feature_3_spaced_picture feature_3_spaced_picture--right' %>
    </div>
  </div>
</div>

<div class='container feature_4_window'>
  <div class='feature_4_window_title'>Highest Rated</div>
  <div class='row'>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "Electric_Love.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "SpiritWolf1.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "dream-glade-metta-simon-haiduk.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "totemical_2.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
  </div>
</div>

<div class='container feature_4_window'>
  <div class='feature_4_window_title'>Whats Hot</div>
  <div class='row'>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "autumn_sky_1.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "lundesigns_holy_spirit.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "jake_amason_genesis.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "Elk_Lake_large.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
  </div>
</div>

<div class='container feature_4_window'>
  <div class='feature_4_window_title'>Freshly Added</div>
  <div class='row'>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "The-Luminous-Return.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "phresha_1.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "totemical_1.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
    <div class='col-md-3 feature_4'>
      <%= link_to items_show_path do %>
        <%= image_tag "lundesigns_subspace.jpg", :class => 'feature_4_picture' %>
      <% end %>
    </div>
  </div>
</div>

<div class='container browse_bar end_div'>
  <div class='row'>
    <div class='col-md-12'>
      <div id='browse_bar_header_bar'></div>
    </div>
  </div>
  <div class='row'>
    <div class='col-md-12 browse_bar_column_container'>
      <div class='browse_bar_column' id='browse_bar_column_1'>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
      </div>
      <div class='browse_bar_column' id='browse_bar_column_2'>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
      </div>
      <div class='browse_bar_column' id='browse_bar_column_3'>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
        <div class='browse_bar_item'>
          <%= link_to items_show_path do %>
            <%= image_tag "prophecy-of-time-justin-totemical.jpg", :class => 'browse_bar_picture' %>
          <% end %>
          <p class='browse_bar_item_name'>Prophecy Of Time by Justin Totemical</p>
        </div>
      </div>
    </div>
  </div>
</div>





<div class='container'>
  <div class='row'>

  </div>
</div>











<!-- <div class='col-md-4 browse_bar_column'>

  <%= image_tag "The-Luminous-Return.jpg", :class => 'browse_bar_picture' %>
  <%= image_tag "The-Luminous-Return.jpg", :class => 'browse_bar_picture' %>
</div>
<div class='col-md-4 browse_bar_column'>
  <%= image_tag "The-Luminous-Return.jpg", :class => 'browse_bar_picture' %>
  <%= image_tag "The-Luminous-Return.jpg", :class => 'browse_bar_picture' %>
  <%= image_tag "The-Luminous-Return.jpg", :class => 'browse_bar_picture' %>
</div>
<div class='col-md-4 browse_bar_column'>
  <%= image_tag "The-Luminous-Return.jpg", :class => 'browse_bar_picture' %>
  <%= image_tag "The-Luminous-Return.jpg", :class => 'browse_bar_picture' %>
  <%= image_tag "The-Luminous-Return.jpg", :class => 'browse_bar_picture' %>
</div> -->